"""Module providing all tiles of the green army"""

outpost=[{"kind": "base",
            "army_name":"outpost",
            "id_tile":"outpost-qg",
            "initiative": [0],
            "range_attacks_direction":None,
            "range_attacks_power":None,
            "cac_attacks_direction":[(0, -1, +1), 
                                    (1, -1, 0),
                                    (1, 0, -1),
                                    (0, 1, -1),
                                    (-1, 1, 0),
                                    (-1, 0, 1)
                                    ],
            "cac_attacks_power":[1,1,1,1,1,1],
            "net":None,
            "life_point":20,
            "shields_position":None,
            "special_capacities":None,
            "module":None,
            "action":None,
            "url_image":"image/armies/outpost-qg.png"},
        {"kind": "unite",
            "army_name":"outpost",
            "id_tile":"outpost-coureur1",
            "initiative": [2],
            "range_attacks_direction":None,
            "range_attacks_power":None,
            "cac_attacks_direction":[(-1,0,1)],
            "cac_attacks_power":[1],
            "net":None,
            "life_point":1,
            "shields_position":None,
            "special_capacities":['movement'],
            "module":None,
            "action":None,
            "url_image":"image/armies/outpost-coureur.png"},
        {"kind": "unite",
            "army_name":"outpost",
            "id_tile":"outpost-coureur2",
            "initiative": [2],
            "range_attacks_direction":None,
            "range_attacks_power":None,
            "cac_attacks_direction":[(-1,0,1)],
            "cac_attacks_power":[1],
            "net":None,
            "life_point":1,
            "shields_position":None,
            "special_capacities":['movement'],
            "module":None,
            "action":None,
            "url_image":"image/armies/outpost-coureur.png"},
            {"kind": "unite",
            "army_name":"outpost",
            "id_tile":"outpost-commando1",
            "initiative": [3],
            "range_attacks_direction":[(1,0,-1)],
            "range_attacks_power":[1],
            "cac_attacks_direction":None,
            "cac_attacks_power":None,
            "net":None,
            "life_point":1,
            "shields_position":None,
            "special_capacities":None,
            "module":None,
            "action":None,
            "url_image":"image/armies/outpost-commando.png"},
            {"kind": "unite",
            "army_name":"outpost",
            "id_tile":"outpost-commando2",
            "initiative": [3],
            "range_attacks_direction":[(1,0,-1)],
            "range_attacks_power":[1],
            "cac_attacks_direction":None,
            "cac_attacks_power":None,
            "net":None,
            "life_point":1,
            "shields_position":None,
            "special_capacities":None,
            "module":None,
            "action":None,
            "url_image":"image/armies/outpost-commando.png"},
            {"kind": "unite",
            "army_name":"outpost",
            "id_tile":"outpost-commando3",
            "initiative": [3],
            "range_attacks_direction":[(1,0,-1)],
            "range_attacks_power":[1],
            "cac_attacks_direction":None,
            "cac_attacks_power":None,
            "net":None,
            "life_point":1,
            "shields_position":None,
            "special_capacities":None,
            "module":None,
            "action":None,
            "url_image":"image/armies/outpost-commando.png"},
            {"kind": "unite",
            "army_name":"outpost",
            "id_tile":"outpost-commando4",
            "initiative": [3],
            "range_attacks_direction":[(1,0,-1)],
            "range_attacks_power":[1],
            "cac_attacks_direction":None,
            "cac_attacks_power":None,
            "net":None,
            "life_point":1,
            "shields_position":None,
            "special_capacities":None,
            "module":None,
            "action":None,
            "url_image":"image/armies/outpost-commando.png"},
            {"kind": "unite",
            "army_name":"outpost",
            "id_tile":"outpost-commando5",
            "initiative": [3],
            "range_attacks_direction":[(1,0,-1)],
            "range_attacks_power":[1],
            "cac_attacks_direction":None,
            "cac_attacks_power":None,
            "net":None,
            "life_point":1,
            "shields_position":None,
            "special_capacities":None,
            "module":None,
            "action":None,
            "url_image":"image/armies/outpost-commando.png"},
            {"kind": "unite",
            "army_name":"outpost",
            "id_tile":"outpost-blindemobile",
            "initiative": [3, 2],
            "range_attacks_direction":[(-1,0,1)],
            "range_attacks_power":[1],
            "cac_attacks_direction":[(0,-1,1)],
            "cac_attacks_power":[2],
            "net":None,
            "life_point":1,
            "shields_position":None,
            "special_capacities":['movement'],
            "module":None,
            "action":None,
            "url_image":"image/armies/outpost-blindemobile.png"},
            {"kind": "unite",
            "army_name":"outpost",
            "id_tile":"outpost-mitrailleuselourde",
            "initiative": [2, 1],
            "range_attacks_direction":[(0, -1, +1)],
            "range_attacks_power":[1],
            "cac_attacks_direction":None,
            "cac_attacks_power":None,
            "net":None,
            "life_point":1,
            "shields_position":None,
            "special_capacities":None,
            "module":None,
            "action":None,
            "url_image":"image/armies/outpost-mitrailleuselourde.png"},
        {"kind": "unite",
        "army_name":"outpost",
        "id_tile":"outpost-exterminateur1",
            "initiative": [2],
            "range_attacks_direction":[(1, 1, 0)],
            "range_attacks_power":[2],
            "cac_attacks_direction":None,
            "cac_attacks_power":None,
            "net":None,
            "life_point":1,
            "shields_position":None,
            "special_capacities":None,
            "module":None,
            "action":None,
            "url_image":"image/armies/outpost-exterminateur.png"},
        {"kind": "unite",
        "army_name":"outpost",
        "id_tile":"outpost-exterminateur2",
            "initiative": [2],
            "range_attacks_direction":[(1, 1, 0)],
            "range_attacks_power":[2],
            "cac_attacks_direction":None,
            "cac_attacks_power":None,
            "net":None,
            "life_point":1,
            "shields_position":None,
            "special_capacities":None,
            "module":None,
            "action":None,
            "url_image":"image/armies/outpost-exterminateur.png"},
        {"kind": "unite",
        "army_name":"outpost",
        "id_tile":"outpost-bagarreur",
            "initiative": [3],
            "range_attacks_direction":None,
            "range_attacks_power":None,
            "cac_attacks_direction":[(0, -1, +1)],
            "cac_attacks_power":[2],
            "net":None,
            "life_point":1,
            "shields_position":None,
            "special_capacities":None,
            "module":None,
            "action":None,
            "url_image":"image/armies/outpost-bagarreur.png"},
        {"kind": "module",
        "army_name":"outpost",
        "id_tile":"outpost-saboteur",
            "initiative": None,
            "range_attacks_direction":None,
            "range_attacks_power":None,
            "cac_attacks_direction":None,
            "cac_attacks_power":None,
            "net":None,
            "life_point":1,
            "shields_position":None,
            "special_capacities":None,
            "module":[{"saboteur":[(0, -1, +1), 
                                    (1, -1, 0),
                                    (1, 0, -1),
                                    (0, 1, -1),
                                    (-1, 1, 0),
                                    (-1, 0, 1)
                                    ]}],
            "action":None,
            "url_image":"image/armies/outpost-saboteur.png"},
        {"kind": "module",
            "army_name":"outpost",
            "id_tile":"outpost-medecin1",
            "initiative": None,
            "range_attacks_direction":None,
            "range_attacks_power":None,
            "cac_attacks_direction":None,
            "cac_attacks_power":None,
            "net":None,
            "life_point":1,
            "shields_position":None,
            "special_capacities":None,
            "module":[{"medic":[(-1, 0, 1),(0, -1, +1), (1, -1, 0)]}],
            "action":None,
            "url_image":"image/armies/outpost-medecin.png"},
        {"kind": "module",
            "army_name":"outpost",
            "id_tile":"outpost-medecin2",
            "initiative": None,
            "range_attacks_direction":None,
            "range_attacks_power":None,
            "cac_attacks_direction":None,
            "cac_attacks_power":None,
            "net":None,
            "life_point":1,
            "shields_position":None,
            "special_capacities":None,
            "module":[{"medic":[(-1, 0, 1),(0, -1, +1), (1, -1, 0)]}],
            "action":None,
            "url_image":"image/armies/outpost-medecin.png"},
        {"kind": "module",
        "army_name":"outpost",
        "id_tile":"outpost-derivateur",
            "initiative": None,
            "range_attacks_direction":None,
            "range_attacks_power":None,
            "cac_attacks_direction":None,
            "cac_attacks_power":None,
            "net":None,
            "life_point":1,
            "shields_position":None,
            "special_capacities":None,
            "module":[{"scoper":[(0, -1, +1), 
                                    (1, -1, 0),
                                    (1, 0, -1),
                                    (0, 1, -1),
                                    (-1, 1, 0),
                                    (-1, 0, 1)
                                    ]}],
            "action":None,
            "url_image":"image/armies/outpost-derivateur.png"},
        {"kind": "module",
        "army_name":"outpost",
        "id_tile":"outpost-centrereconnaissance",
            "initiative": None,
            "range_attacks_direction":None,
            "range_attacks_power":None,
            "cac_attacks_direction":None,
            "cac_attacks_power":None,
            "net":None,
            "life_point":1,
            "shields_position":None,
            "special_capacities":None,
            "module":[{'doublemove':None}],
            "action":None,
            "url_image":"image/armies/outpost-centrereconnaissance.png"},
            {"kind": "module",
            "army_name":"outpost",
            "id_tile":"outpost-officier",
            "initiative": None,
            "range_attacks_direction":None,
            "range_attacks_power":None,
            "cac_attacks_direction":None,
            "cac_attacks_power":None,
            "net":None,
            "life_point":1,
            "shields_position":None,
            "special_capacities":None,
            "module":[{"range_augment":[(0, -1, +1), 
                                    (1, -1, 0),
                                    (1, 0, -1),
                                    (0, 1, -1),
                                    (-1, 1, 0),
                                    (-1, 0, 1)
                                    ]}],
            "action":None,
            "url_image":"image/armies/outpost-officier.png"},
        {"kind": "module",
        "army_name":"outpost",
        "id_tile":"outpost-eclaireur1",
            "initiative": None,
            "range_attacks_direction":None,
            "range_attacks_power":None,
            "cac_attacks_direction":None,
            "cac_attacks_power":None,
            "net":None,
            "life_point":1,
            "shields_position":None,
            "special_capacities":None,
            "module":[{"initiative_augment":[(0, -1, +1),
                                            (1, 0, -1),
                                            (-1, 1, 0),
                                            ]}],
            "action":None,
            "url_image":"image/armies/outpost-eclaireur.png"},
        {"kind": "module",
        "army_name":"outpost",
        "id_tile":"outpost-eclaireur2",
            "initiative": None,
            "range_attacks_direction":None,
            "range_attacks_power":None,
            "cac_attacks_direction":None,
            "cac_attacks_power":None,
            "net":None,
            "life_point":1,
            "shields_position":None,
            "special_capacities":None,
            "module":[{"initiative_augment":[(0, -1, +1),
                                            (1, 0, -1),
                                            (-1, 1, 0),
                                            ]}],
            "action":None,
            "url_image":"image/armies/outpost-eclaireur.png"},
        {"kind": "action",
        "army_name":"outpost",
        "id_tile":"outpost-battle1",
            "initiative": None,
            "range_attacks_direction":None,
            "range_attacks_power":None,
            "cac_attacks_direction":None,
            "cac_attacks_power":None,
            "net":None,
            "life_point":None,
            "shields_position":None,
            "special_capacities":None,
            "module":None,
            "action":"battle",
            "url_image":"image/armies/outpost-battle.png"},
        {"kind": "action",
        "army_name":"outpost",
        "id_tile":"outpost-battle2",
            "initiative": None,
            "range_attacks_direction":None,
            "range_attacks_power":None,
            "cac_attacks_direction":None,
            "cac_attacks_power":None,
            "net":None,
            "life_point":None,
            "shields_position":None,
            "special_capacities":None,
            "module":None,
            "action":"battle",
            "url_image":"image/armies/outpost-battle.png"},
        {"kind": "action",
        "army_name":"outpost",
        "id_tile":"outpost-battle3",
            "initiative": None,
            "range_attacks_direction":None,
            "range_attacks_power":None,
            "cac_attacks_direction":None,
            "cac_attacks_power":None,
            "net":None,
            "life_point":None,
            "shields_position":None,
            "special_capacities":None,
            "module":None,
            "action":"battle",
            "url_image":"image/armies/outpost-battle.png"},
        {"kind": "action",
        "army_name":"outpost",
        "id_tile":"outpost-battle4",
            "initiative": None,
            "range_attacks_direction":None,
            "range_attacks_power":None,
            "cac_attacks_direction":None,
            "cac_attacks_power":None,
            "net":None,
            "life_point":None,
            "shields_position":None,
            "special_capacities":None,
            "module":None,
            "action":"battle",
            "url_image":"image/armies/outpost-battle.png"},
        {"kind": "action",
        "army_name":"outpost",
        "id_tile":"outpost-battle5",
            "initiative": None,
            "range_attacks_direction":None,
            "range_attacks_power":None,
            "cac_attacks_direction":None,
            "cac_attacks_power":None,
            "net":None,
            "life_point":None,
            "shields_position":None,
            "special_capacities":None,
            "module":None,
            "action":"battle",
            "url_image":"image/armies/outpost-battle.png"},
        {"kind": "action",
        "army_name":"outpost",
        "id_tile":"outpost-battle6",
            "initiative": None,
            "range_attacks_direction":None,
            "range_attacks_power":None,
            "cac_attacks_direction":None,
            "cac_attacks_power":None,
            "net":None,
            "life_point":None,
            "shields_position":None,
            "special_capacities":None,
            "module":None,
            "action":"battle",
            "url_image":"image/armies/outpost-battle.png"},
        {"kind": "action",
        "army_name":"outpost",
        "id_tile":"outpost-mouvement1",
            "initiative": None,
            "range_attacks_direction":None,
            "range_attacks_power":None,
            "cac_attacks_direction":None,
            "cac_attacks_power":None,
            "net":None,
            "life_point":None,
            "shields_position":None,
            "special_capacities":None,
            "module":None,
            "action":"movement",
            "url_image":"image/armies/outpost-mouvement.png"},
        {"kind": "action",
        "army_name":"outpost",
        "id_tile":"outpost-mouvement2",
            "initiative": None,
            "range_attacks_direction":None,
            "range_attacks_power":None,
            "cac_attacks_direction":None,
            "cac_attacks_power":None,
            "net":None,
            "life_point":None,
            "shields_position":None,
            "special_capacities":None,
            "module":None,
            "action":"movement",
            "url_image":"image/armies/outpost-mouvement.png"},
        {"kind": "action",
        "army_name":"outpost",
        "id_tile":"outpost-mouvement3",
            "initiative": None,
            "range_attacks_direction":None,
            "range_attacks_power":None,
            "cac_attacks_direction":None,
            "cac_attacks_power":None,
            "net":None,
            "life_point":None,
            "shields_position":None,
            "special_capacities":None,
            "module":None,
            "action":"movement",
            "url_image":"image/armies/outpost-mouvement.png"},
        {"kind": "action",
        "army_name":"outpost",
        "id_tile":"outpost-mouvement4",
            "initiative": None,
            "range_attacks_direction":None,
            "range_attacks_power":None,
            "cac_attacks_direction":None,
            "cac_attacks_power":None,
            "net":None,
            "life_point":None,
            "shields_position":None,
            "special_capacities":None,
            "module":None,
            "action":"movement",
            "url_image":"image/armies/outpost-mouvement.png"},
        {"kind": "action",
        "army_name":"outpost",
        "id_tile":"outpost-mouvement5",
            "initiative": None,
            "range_attacks_direction":None,
            "range_attacks_power":None,
            "cac_attacks_direction":None,
            "cac_attacks_power":None,
            "net":None,
            "life_point":None,
            "shields_position":None,
            "special_capacities":None,
            "module":None,
            "action":"movement",
            "url_image":"image/armies/outpost-mouvement.png"},
        {"kind": "action",
        "army_name":"outpost",
        "id_tile":"outpost-mouvement6",
            "initiative": None,
            "range_attacks_direction":None,
            "range_attacks_power":None,
            "cac_attacks_direction":None,
            "cac_attacks_power":None,
            "net":None,
            "life_point":None,
            "shields_position":None,
            "special_capacities":None,
            "module":None,
            "action":"movement",
            "url_image":"image/armies/outpost-mouvement.png"},
        {"kind": "action",
        "army_name":"outpost",
        "id_tile":"outpost-mouvement7",
            "initiative": None,
            "range_attacks_direction":None,
            "range_attacks_power":None,
            "cac_attacks_direction":None,
            "cac_attacks_power":None,
            "net":None,
            "life_point":None,
            "shields_position":None,
            "special_capacities":None,
            "module":None,
            "action":"movement",
            "url_image":"image/armies/outpost-mouvement.png"},
        {"kind": "action",
        "army_name":"outpost",
        "id_tile":"outpost-sniper",
            "initiative": None,
            "range_attacks_direction":None,
            "range_attacks_power":None,
            "cac_attacks_direction":None,
            "cac_attacks_power":None,
            "net":None,
            "life_point":None,
            "shields_position":None,
            "special_capacities":None,
            "module":None,
            "action":"sniper",
            "url_image":"image/armies/outpost-sniper.png"}
        ]
